/**
 * Builds the show-agnostic season file (src/data/seasons/dwts-s35.json) and supabase/seed.sql
 * from the copied live data files (tests/fixtures/live-data). Only show/season facts are used:
 * contestants, weekly scores, eliminations, schedule. No league data goes into the seed.
 *   npm run seed:generate
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { LegacySchedule, LegacyScores, LegacySeason } from "../src/lib/scoring/legacy";
import type { SeasonFile } from "../src/lib/data/season-file";
import { DWTS_TEMPLATE } from "../src/lib/scoring/templates";
import { monogram } from "../src/lib/data/monogram";
import { seasonFileFromLegacy } from "../src/lib/migration/season-from-legacy";

const dir = join(__dirname, "..", "tests", "fixtures", "live-data");
const read = <T>(f: string): T => JSON.parse(readFileSync(join(dir, f), "utf8"));
const season = read<LegacySeason>("season.json");
const scores = read<LegacyScores>("scores.json");
const schedule = read<LegacySchedule>("elimination-schedule.json");

const file: SeasonFile = seasonFileFromLegacy(season, scores, schedule);
writeFileSync(join(__dirname, "..", "src", "data", "seasons", "dwts-s35.json"), JSON.stringify(file, null, 2) + "\n");

const q = (s: string | null | undefined) => (s == null ? "null" : `'${String(s).replace(/'/g, "''")}'`);
const lines: string[] = [
  "-- GENERATED by scripts/generate-seed.ts from the live data files. Do not edit by hand.",
  "-- Seeds shared show data only: DWTS Season 35 (show-agnostic format) + the ballroom scoring template.",
  "begin;",
  `insert into public.shows (slug, name, unit_label) values (${q(file.show.slug)}, ${q(file.show.name)}, ${q(file.show.unitLabel)}) on conflict (slug) do nothing;`,
  `insert into public.scoring_templates (slug, name, description, formula) values (${q(DWTS_TEMPLATE.slug)}, ${q(DWTS_TEMPLATE.name)}, ${q(DWTS_TEMPLATE.description)}, ${q(JSON.stringify({ type: "score_over_max_x_round_value", max_score: DWTS_TEMPLATE.rules.maxScore, round_values: DWTS_TEMPLATE.rules.roundValues, split: DWTS_TEMPLATE.split, max_possible: DWTS_TEMPLATE.maxPossible }))}::jsonb) on conflict (slug) do nothing;`,
  `insert into public.seasons (show_id, number, title, copies_per_contestant, roster_size, default_scoring_template_id, status, finale_date)
  select s.id, ${file.season.number}, ${q(file.season.title)}, ${file.season.copiesPerContestant}, ${q(JSON.stringify(file.season.rosterSize))}::jsonb, t.id, ${q(file.season.status)}, ${q(file.season.finaleDate)}::date
  from public.shows s, public.scoring_templates t where s.slug = ${q(file.show.slug)} and t.slug = ${q(DWTS_TEMPLATE.slug)}
  on conflict (show_id, number) do nothing;`,
  `create temp table _season on commit drop as select se.id from public.seasons se join public.shows sh on sh.id = se.show_id where sh.slug = ${q(file.show.slug)} and se.number = ${file.season.number};`,
];
file.units.forEach((u, i) => {
  lines.push(`insert into public.contestant_units (season_id, key, label, sort_order) select id, ${q(u.key)}, ${q(u.members.map((m) => m.name).join(" & "))}, ${i} from _season on conflict do nothing;`);
  u.members.forEach((m, j) =>
    lines.push(`insert into public.contestants (season_id, unit_id, key, name, role, monogram, sort_order) select s.id, cu.id, ${q(m.key)}, ${q(m.name)}, ${q(m.role)}, ${q(monogram(m.name))}, ${i * 10 + j} from _season s join public.contestant_units cu on cu.season_id = s.id and cu.key = ${q(u.key)} on conflict do nothing;`),
  );
});
for (const e of file.episodes) {
  lines.push(`insert into public.episodes (season_id, number, name, round_value, max_score, units_competing, schedule_status) select id, ${e.number}, ${q(e.name)}, ${e.roundValue}, ${e.maxScore}, ${e.unitsCompeting ?? "null"}, ${q(e.scheduleStatus)} from _season on conflict do nothing;`);
  for (const r of e.results)
    lines.push(`insert into public.scores (episode_id, unit_id, raw_score, eliminated, source) select ep.id, cu.id, ${r.score}, ${r.eliminated}, 'auto' from _season s join public.episodes ep on ep.season_id = s.id and ep.number = ${e.number} join public.contestant_units cu on cu.season_id = s.id and cu.key = ${q(r.unit)} on conflict do nothing;`);
}
lines.push("commit;", "");
writeFileSync(join(__dirname, "..", "supabase", "seed.sql"), lines.join("\n"));
console.log(`season file: ${file.units.length} units, ${file.episodes.length} episodes, ${file.episodes.reduce((n, e) => n + e.results.length, 0)} scores; seed.sql: ${lines.length} lines`);
